language: java
jdk:
- oraclejdk8
sudo: false

script: script: gradle executeFeatures –Pemail=$email –Ppassword=$password –PapiToken=$apiToken -PcucumberOptions="--tags @smoke"
branches:
  only:
   - develop
   - ContinousIntegration
notifications:
 email:
 - Rosario.Garcia@fundacion-jala.org
 - Bruno.Barrios@fundacion-jala.org
